[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"

# Form success redirect
[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 301
